<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZk8v2eq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZk8v2eq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZk8v2eq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZk8v2eq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZk8v2eq\appProdProjectContainer([
    'container.build_hash' => 'Zk8v2eq',
    'container.build_id' => 'c0608178',
    'container.build_time' => 1599933244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZk8v2eq');
